---
title: "K-means Clustering by Total Drinks Per Trimester for Participants With Three Completed Trimesters in the South Africa Site"
author: "Melissa Nuñez"
date: "4/23/2018"
output: html_document
---

```{r setup, include=FALSE}
library(kml)
library(ggplot2)
library(gridExtra)
library(reshape2)
library(psych)
library(kableExtra)

# Read in datasets
alcohol=read.csv('/Users/user/Dropbox/Melissa/PASS/data/adalc_patid.csv')
smoke=read.csv('/Users/user/Dropbox/Melissa/PASS/data/adsmk_patid.csv')
load('/Users/user/Dropbox/Melissa/PASS/kml_cluster_v1_20180426/PASS_allparticipants_v1_20180421.Rdata')

# Create function to run k-means clustering
runkml<-function(data, variable.loc, time=c(1,2,3),newvar='cluster'){
  set.seed(123456)
  cld <- cld(data,timeInData=variable.loc,time=time)
  kml(cld,nbClusters=4:7,nbRedrawing=20)
#  try(choice(cld))
  a=plotAllCriterion(cld,CRITERION_NAMES[4])
  return(cld)
}
```

### Citerion for cluster sizes (k) is plotted, however we decided prior to analysis that k should be 4
#### For exposure definition, d0s0 - did not smoke or drink, d0s1 - did not drink, but did smoke, etc
```{r,echo=FALSE}
# Subset data where BISH is ID for Cape Town, South Africa
pass.SA.completers = merge[merge$site=='BISH' & merge$TotalStdDrinks_Num_Avai_tri==3,]

# Merge the 'TotalStdDrinksT1, TotalStdDrinksT2, TotalStdDrinksT3'
drinkvars=names(merge)[grep('TotalStdDrinksT',names(merge))]

# Run KML for exposed patients only
cld.SA.TotalStdDrinks=runkml(pass.SA.completers[pass.SA.completers$total_exposure_both!='d0s0',], grep('TotalStdDrinksT',names(merge)))

# Create 'Cluster.TotalStdDrinks' column
pass.SA.completers$Cluster.TotalStdDrinks<-NA

# Enter 'N' in the 'Cluster.TotalStdDrinks' column for all nonexposed patients
pass.SA.completers$Cluster.TotalStdDrinks[pass.SA.completers$total_exposure_both=='d0s0']='N'

# Input cluster number for each patient into the 'Cluster.TotalStdDrinks' column
pass.SA.completers$Cluster.TotalStdDrinks[pass.SA.completers$total_exposure_both!='d0s0']=getClusters(cld.SA.TotalStdDrinks,4)

# Tables for sample size and clusters (i.e. descriptive stats)
StdDrinks.count <- table(pass.SA.completers$Cluster.TotalStdDrinks)
StdDrinks.Prop <- round(prop.table(StdDrinks.count)*100, digits = 1)
StdDrinks.Cum <- round((cumsum(StdDrinks.count)/(dim(pass.SA.completers)[1]))*100, digits = 1)
StdDrinks.Table <- data.frame(cbind(StdDrinks.count,StdDrinks.Prop, StdDrinks.Cum))
binded <- rbind(StdDrinks.Table,"Sum" = colSums(StdDrinks.Table[1:2]))
binded[6,3] <- ""

Drinks.count.kable <- kable(binded, col.names = c("N","Raw %","Cumulative %"), "html", caption = "Subject Count Per Cluster")
kable_styling(Drinks.count.kable, bootstrap_options = c("striped", "hover"), full_width = F, position = "left")

CrossTab.Drinks <- addmargins(xtabs(~Cluster.TotalStdDrinks+total_exposure_both, data = pass.SA.completers))

Drinks.prop.kable <- kable(CrossTab.Drinks, "html", caption = "Subject Count Grouped by Cluster and Exposure")
kable_styling(Drinks.prop.kable, bootstrap_options = c("striped", "hover"), full_width = F, position = "left")

# Plotting the cluster trajectories
ggplot(melt(pass.SA.completers[,c("patid","Cluster.TotalStdDrinks", drinkvars)], id=c('patid','Cluster.TotalStdDrinks')), aes(x=variable,y=value, group=patid, colour=Cluster.TotalStdDrinks)) + 
stat_summary(aes(y = value,group = Cluster.TotalStdDrinks), fun.y=mean, geom="line",size=2) +
theme(legend.position=c(0.8,0.8)) + ggtitle("Total Drinks Per Trimester Grouped by Cluster")


ggplot(melt(pass.SA.completers[,c("patid","Cluster.TotalStdDrinks", drinkvars)], id=c('patid','Cluster.TotalStdDrinks')), aes(x=variable,y=value, group=patid, colour=Cluster.TotalStdDrinks)) + 
geom_line(size=0.01,linetype = 1) + 
stat_summary(aes(y = value,group = Cluster.TotalStdDrinks), fun.y=mean, geom="line",size=2) + 
ggtitle("Total Drinks Per Trimester Grouped by Cluster")


ggplot(melt(pass.SA.completers[,c("patid","Cluster.TotalStdDrinks", drinkvars)], id=c('patid','Cluster.TotalStdDrinks')), aes(x=variable,y=value, group=patid, colour=Cluster.TotalStdDrinks)) + 
geom_line(size=0.01,linetype = 1) + 
stat_summary(aes(y = value,group = Cluster.TotalStdDrinks), fun.y=mean, geom="line",size=2) + 
scale_x_discrete(labels=c("T1","T2","T3")) + 
facet_grid(. ~ Cluster.TotalStdDrinks) + 
ggtitle("Total Drinks Per Trimester Grouped by Cluster")

```
